status = [
  "Check (default)",
  "Check (pbjson)",
  "Check (serde)",
  "Test (default)",
  "Test (pbjson)",
  "Test (serde)",
  "Rustfmt",
  "Clippy (default)",
  "Clippy (pbjson)",
  "Clippy (serde)",
  "Rustdoc",
]
delete_merged_branches = true
timeout_sec = 600
