# SPDX-License-Identifier: Apache-2.0

name: Merge

on:
  push:
    branches:
      - trying # always pass on trying because commit message is not configurable
      - staging

jobs:
  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - if: github.ref == 'refs/heads/staging'
        uses: actions/checkout@v3
      - if: github.ref == 'refs/heads/staging'
        uses: actions/setup-node@v3
      - if: github.ref == 'refs/heads/staging'
        run: |
          npm install @commitlint/config-conventional
          echo "${{ github.event.head_commit.message }}" | npx commitlint --extends @commitlint/config-conventional
